language: go

go:
  - 1.5
  - 1.6

addons:
  apt:
    packages:
      - python-virtualenv

before_script:
  - virtualenv env
  - env/bin/pip install -r tests/requirements.txt

script:
  - go build
  - cd tests && ../env/bin/python -m unittest test
